name: CI Autofix (Optimized)

on:
  workflow_run:
    workflows: ["RN Unit CI"]
    types: [completed]

jobs:
  autofix_request:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 大幅に短縮
    permissions:
      pull-requests: write

    steps:
      - name: Post autofix request
        uses: actions/github-script@v7
        env:
          TRIGGERING_RUN_ID: ${{ github.event.workflow_run.id }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          PULL_REQUESTS_JSON: ${{ toJson(github.event.workflow_run.pull_requests) || '[]' }}
        with:
          script: |
            const triggering_run_id = process.env.TRIGGERING_RUN_ID;
            const head_branch = process.env.HEAD_BRANCH;
            let pull_requests = [];
            
            try {
              pull_requests = JSON.parse(process.env.PULL_REQUESTS_JSON);
            } catch (e) {
              console.error("Error parsing PULL_REQUESTS_JSON:", e);
              return;
            }

            // PRが存在する場合のみコメント投稿
            if (pull_requests && pull_requests.length > 0) {
              const prNumber = pull_requests[0].number;
              
              // シンプルなコメント（ログ取得処理を削除）
              const commentBody = `@claude CI (ワークフロー: RN Unit CI) が失敗しました。

            **失敗情報:**
            - ワークフロー実行ID: ${triggering_run_id}
            - ブランチ: ${head_branch}
            - 実行ログ: https://github.com/${{ github.repository }}/actions/runs/${triggering_run_id}

            エラーログを確認して修正案を提案してください。修正後は \`npm test\` でテストが通ることを確認してください。`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
              
              console.log(`Autofix request posted to PR #${prNumber}`);
            } else {
              console.log('No associated PR found. Skipping autofix request.');
            } 