name: Claude Manual Request

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  # PR本文の@claudeもトリガーに含めるか検討 (今回はコメントのみに絞る)

jobs:
  claude_manual_response:
    # コメント本文に @claude が含まれている場合のみ実行
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: claude-manual-${{ github.event.issue.number || github.event.pull_request.number }}-${{ github.event.comment.id }}
      cancel-in-progress: false # 手動リクエストは中断しない
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # PRコメントの場合はPRのHEADを、Issueコメントの場合はデフォルトブランチをチェックアウト
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Claude Code Response
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_phrase: "@claude" # これをトリガーとしてClaudeがメンション以降の指示を読み取る
          timeout_minutes: "25"
          allowed_tools: "Bash(git status),Bash(git log),Bash(git diff),Bash(npm install),Bash(npm test),Bash(npm run lint),View,GlobTool,GrepTool,Edit,Bash(pwd),Bash(ls)"
          custom_instructions: |
            あなたはMiraiCare（React Native + TypeScript + Supabase）プロジェクトの専門エンジニアアシスタントです。
            メンションされたコメントの内容に基づいて、開発者の指示に従ってタスクを実行してください。
            指示が不明確な場合は、確認を求めることも可能です。
            コード修正、分析、ドキュメント生成、質問への回答など、広範なリクエストに対応してください。
            日本語で応答し、必要に応じてコードブロックや詳細な説明を含めてください。
          # model_name: claude-3-opus-20240229 # (アクションのデフォルトに任せる)

