name: Claude Code (dynamic model)

on:
  issue_comment: { types: [created] }
  issues:        { types: [opened] }

jobs:
  claude:
    if: startsWith(github.event.comment.body || github.event.issue.body, '@claude')
    runs-on: ubuntu-latest
    timeout-minutes: 6
    concurrency:
      group: ${{ github.event.issue.url || github.event.comment.issue_url }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - id: choose
        run: |
          ./.github/scripts/choose_model.sh \
            "${{ github.event.comment.body || github.event.issue.body }}"

      - uses: anthropics/claude-code-action@v0
        with:
          prompt:               "${{ github.event.comment.body || github.event.issue.body }}"
          anthropic_api_key:    ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_parameters: ${{ steps.choose.outputs.anthropic_parameters }}
          allowed_tools: |
            [
              "GlobTool",
              "GrepTool",
              "LS",
              "Bash(git diff --name-only origin/main)",
              "Bash(npm test)"
            ]
          max_turns: 3 