name: Claude CI Autofix

on:
  workflow_run:
    workflows: ["RN Unit CI"] # test.yml の name を想定
    types: [completed]

jobs:
  autofix:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write # PRへのコメントや修正提案のため
      issues: write # 関連Issueへのコメントのため

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Get failure information
        id: get_failure_info
        uses: actions/github-script@v7
        env: # env を使って必要な値を渡す
          TRIGGERING_RUN_ID: ${{ github.event.workflow_run.id }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          PULL_REQUESTS_JSON: ${{ toJson(github.event.workflow_run.pull_requests) || '[]' }}
        with:
          script: |
            const triggering_run_id = process.env.TRIGGERING_RUN_ID;
            const head_branch = process.env.HEAD_BRANCH; 
            let pull_requests = [];
            try {
              pull_requests = JSON.parse(process.env.PULL_REQUESTS_JSON);
            } catch (e) {
              console.error("Error parsing PULL_REQUESTS_JSON:", e);
              console.log("PULL_REQUESTS_JSON was:", process.env.PULL_REQUESTS_JSON);
            }

            core.setOutput('triggering_run_id', triggering_run_id);
            console.log(`Triggering workflow run ID: ${triggering_run_id}`);

            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: triggering_run_id,
            });
            
            const failedJob = jobs.data.jobs.find(job => job.conclusion === 'failure' && (job.name.includes('test') || job.name.includes('Test'))); 
            
            if (!failedJob) {
              core.setFailed('Failed CI job not found in the triggering workflow run.');
              return;
            }
            core.setOutput('failed_job_name', failedJob.name);
            core.setOutput('failed_job_id', failedJob.id);
            console.log(`Failed Job Name: ${failedJob.name}, ID: ${failedJob.id}`);

            let prNumber = null;
            if (pull_requests && pull_requests.length > 0) {
              prNumber = pull_requests[0].number;
              core.setOutput('pr_number', prNumber);
              console.log(`Associated PR Number: ${prNumber}`);
            } else {
              console.log('No associated PR found for this workflow run. Proceeding without PR context for autofix.');
            }

      - name: Claude Code Autofix
        if: steps.get_failure_info.outputs.failed_job_id # 失敗したジョブIDがあれば実行
        uses: anthropics/claude-code-action@beta 
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          timeout_minutes: "15"
          allowed_tools: "Edit,View,GrepTool,Bash(npm test)"
          custom_instructions: |
            CI (ジョブ名: `${{ steps.get_failure_info.outputs.failed_job_name }}`) が失敗しました。
            関連するエラーログを分析し、問題を特定してコードを修正してください。
            修正はブランチ `${{ github.event.workflow_run.head_branch }}` に直接コミットしてください。
            コミットメッセージは「Fix: Apply Claude auto-fix for CI failure」としてください。
            修正後は `npm test` を実行し、テストが成功することを確認してください。

            **関連情報:**
            - トリガーとなったワークフロー実行ID: ${{ steps.get_failure_info.outputs.triggering_run_id }}
            - 失敗したジョブID: ${{ steps.get_failure_info.outputs.failed_job_id }}
            - 対象ブランチ: ${{ github.event.workflow_run.head_branch }}
            ${{ steps.get_failure_info.outputs.pr_number && format('- 関連プルリクエスト: #{0}', steps.get_failure_info.outputs.pr_number) || '- プルリクエスト情報なし' }}
            
            もしプルリクエストが存在する場合 (#${{ steps.get_failure_info.outputs.pr_number }}) は、修正内容についてコメントもお願いします。
            プルリクエストが存在しない場合は、ブランチへの直接コミットのみを行ってください。 